### ISSUE TITLE
华硕Z9PA-D8双路E5-2670使用你的efi启动不了可以指导一下吗

### ISSUE THREAD

**Issue by bytemt** [cheneyveron/ozmosis-huanan-x79-e5-2670#1]
calling mpo_policy_init for AMFI
Security polic loaded：Apple Mobile File Integrity （AMFI）
Calling mpo_policy_init for Sandbox
Security policy loaded：Seatbelt sandbox policy（sandbox）
Calling mpo_policy_init for Quarantile 
Security policy loaded：Quarantine policy （Quarantine）
Calling mpo_policy_init for TMSafetyNet
IOAPIC：Version 0x20 Vectors 64:87
IOAPIC：Version 0x20 Vectors 88:111
ACPI：Executed 1 blocks of module-level excutable AML code
ACPI：sleep states S4 S5
pci（bulid 20:56:41 Dec 20 2018）,flags 0x20e0080
RTC：Only single R

**Comment by cheneyveron** [comment]
华硕Z9PA-D8不适用与本Repo，建议查看[这个Repo](https://github.com/cheneyveron/clover-x79-e5-2670-gtx650)
如果使用上面的Repo无法启动，请到[这里](https://github.com/cheneyveron/clover-x79-e5-2670-gtx650/issues/new)，按照模板提问哦，记得补充详细说明
